services:
  - type: web
    name: tradepulse-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    healthCheckPath: /
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: CHANNEL_ID
        sync: false
      - key: TWELVE_DATA_API_KEY
        sync: false
      - key: ADMIN_IDS
        value: "[]"